### ISSUE TITLE
Add `arm-small` (and `x64-small`) AMI images

### ISSUE THREAD

**Issue by phlax** [envoyproxy/ci-infra#17]
Some jobs require arm (other than the build/release job) and so currently need to use the `arm-large` image.

Currently this is quite helpful as otherwise these jobs would take a long time, but there are some optimizations im currently working on which will make this less necessary, but we will still need an arm AMI to run on

We might also want something similar for x64 as there are some jobs that might benefit from using a self-hosted image but likewise dont need so much resources - the case is less clear cut here, and im currently testing stuff around this to clarify how we can best optimize this CI

**Comment by phlax** [comment]
cc @mum4k

**Comment by phlax** [comment]
cc @lizan

**Comment by mum4k** [comment]
Looks good to me, this will need some work in AWS (editing the Terraform scripts and adding new pools) and some setup in AZP.

Let me know if you need any advice, I'll help if I can. I can also help out by pushing out the changes. We should probably start by defining the new pools.

**Comment by phlax** [comment]
partial fix in #63
